/rat/db/set DETECTOR experiment "BNL1Ton_Water_FullPMTCoverage"
/rat/db/set DETECTOR geo_file "BNL1ton.geo"

/rat/db/set DAQ noise_flag 0

#/random/setSeeds 1000 1000

/PhysicsList/setOpWLS g4

/run/initialize

# /glg4scint/off
# /glg4scint/maxTracksPerStep 10
# /glg4scint/meanPhotonsPerSecondary 100
# /glg4scint/reemission off
# /glg4scint/setQF 0.001


#/vis/scene/create
#/vis/open OGLIX
#/vis/drawVolume

 #/vis/scene/add/volume
#/vis/scene/add/axes 0 0 0 2 m
#/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/set 1 red
#/vis/modeling/trajectories/drawByCharge-0/set -1 red
#/vis/modeling/trajectories/drawByCharge-0/set 0 blue
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1

#Use filter to draw only the particles
#Use invert to draw all other particles expcet those are in the filter
# /vis/filtering/trajectories/create/particleFilter
# /vis/filtering/trajectories/particleFilter-0/add mu-
# /vis/filtering/trajectories/particleFilter-0/add mu+
# /vis/filtering/trajectories/particleFilter-0/add e-
# /vis/filtering/trajectories/particleFilter-0/add opticalphoton
# /vis/filtering/trajectories/particleFilter-0/invert true
# /vis/filtering/trajectories/particleFilter-0/verbose true
# /vis/filtering/trajectories/particleFilter-0/active false

# /vis/modeling/trajectories/create/drawByParticleID
# /vis/modeling/trajectories/drawByParticleID-0/set mu- red
# /vis/modeling/trajectories/drawByParticleID-0/set mu+ red
# /vis/modeling/trajectories/drawByParticleID-0/set e- red
# /vis/modeling/trajectories/drawByParticleID-0/set opticalphoton red
# /vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# /vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 0.5

# /vis/modeling/trajectories/select drawByParticleID-0


# /vis/ogl/set/displayListLimit 10000000

# /vis/scene/add/hits
# /vis/scene/endOfEventAction accumulate 1
# /vis/viewer/set/autoRefresh true

# /vis/viewer/reset
# /vis/viewer/set/style surface
# /vis/viewer/set/viewpointThetaPhi 60 -60 deg
# /vis/viewer/set/upVector 0 0 1

# /vis/scene/add/axes 0 0 0 500 mm

/tracking/storeTrajectory 0

# BEGIN EVENT LOOP
/rat/proc simpledaq
/rat/proc count
/rat/procset update 1

/rat/proc fitcentroid
/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"

/rat/proclast outroot
/rat/procset file "cosmic_run1025_hodoOnly.root"
#END EVENT LOOP

#/generator/add combo gun:point
#/generator/vtx/set mu-  0 0 0 800
#/generator/pos/set 200 0 1200
#350 nm wavelength
#/generator/vtx/set pi- 0 0 -1 10000
#/generator/pos/set 256.35 -30.79375 250
#/generator/pos/set 300 50 3000

# cosmic_muons_only_3MEvts_box10m_onlyHitCD.dat
# cosmic_events_generated.dat, the first cry muons, 500k.
/generator/add external external:poisson:"cosmic_run1025_HodoOnly.dat"

#/run/verbose 2
#/event/verbose 3
#/tracking/verbose 2

/run/beamOn 100
